[package]
name = "compiler"
version = "0.1.0"
authors = ["aldaronlau"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.asm_riscv]
path = "../asm_riscv"
